server:
  port: 9411

spring:
  application:
    name: zipkin-server

  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false
    
    
zipkin:
  storage:
    type: mysql 
  collector:
    rabbitmq:
      queue: zipkin 
      addresses: localhost:5672
      username: guest
      password: guest